### ISSUE TITLE
Product Variations UI Enhancement: Replace 'Customers Also Bought' with Interactive Variation Selector

### ISSUE THREAD

**Issue by epireve** [epireve/grocerygo#4]
## Overview

The current product detail page has a "Customers also bought" section that displays product variations as separate items leading to different pages. This creates a poor user experience and inconsistent UI. We need to redesign this section as an interactive product variation selector that allows users to choose different SKUs/variations and add them to cart without page navigation.

### Example URL: `http://127.0.0.1:8000/product/alkaline-water-air-alkali/`

**Current Flow:**
1. User views main product: "Alkaline Water / Air Alkali" (RM3.50)
2. "Customers also bought" section shows:
   - No image - Alkaline Water / Air Alkali - 1L (RM3.50)
   - No image - Alkaline Water / Air Alkali - 2L (RM5.90)
   - No image - Alkaline Water / Air Alkali - 500ml (RM1.90)
   - No image - Alkaline Water / Air Alkali - 6-Pack (6x500ml) (RM10.90)
3. Clicking any item navigates to a separate product page
4. User must navigate back to original page

**Problems:**
- Misleading section title ("Customers also bought")
- Poor UX with multiple page navigations
- Inconsistent UI with missing images
- These are actually product variations, not related products
- No clear way to compare variations side-by-side

### New Design Concept

```html
<!-- Product Variation Selector -->
<div class="product-variations">
    <h3>Available Sizes</h3>
    <div class="variation-options">
        <div class="variation-option">
            <input type="radio" id="size-500ml" name="product_variation" value="alkaline-water-500ml" data-price="1.90">
            <label for="size-500ml" class="variation-label">
                <span class="variation-size">500ml</span>
                <span class="variation-price">RM1.90</span>
            </label>
        </div>
        <div class="variation-option">
            <input type="radio" id="size-1l" name="product_variation" value="alkaline-water-1l" data-price="3.50" checked>
            <label for="size-1l" class="variation-label">
                <span class="variation-size">1L</span>
                <span class="variation-price">RM3.50</span>
            </label>
        </div>
        <div class="variation-option">
            <input type="radio" id="size-2l" name="product_variation" value="alkaline-water-2l" data-price="5.90">
            <label for="size-2l" class="variation-label">
                <span class="variation-size">2L</span>
                <span class="variation-price">RM5.90</span>
            </label>
        </div>
        <div class="variation-option">
            <input type="radio" id="size-6pack" name="product_variation" value="alkaline-water-6pack" data-price="10.90">
            <label for="size-6pack" class="variation-label">
                <span class="variation-size">6-Pack (6x500ml)</span>
                <span class="variation-price">RM10.90</span>
            </label>
        </div>
    </div>
    
    <!-- Dynamic Add to Cart Section -->
    <div class="variation-cart-section">
        <div class="selected-variation-info">
            <span class="selected-title" id="selected-title">Alkaline Water / Air Alkali - 1L</span>
            <span class="selected-price" id="selected-price">RM3.50</span>
        </div>
        <div class="quantity-selector">
            <label for="quantity">Quantity:</label>
            <input type="number" id="quantity" name="quantity" value="1" min="1" max="10">
        </div>
        <button type="button" class="btn btn-primary add-to-cart-variation" data-product-id="">
            Add to Cart
        </button>
    </div>
</div>
```

### CSS Styling

```css
/* Product Variations Styling */
.product-variations {
    margin: 2rem 0;
    padding: 1.5rem;
    border: 1px solid #e0e0e0;
    border-radius: 8px;
    background-color: #f9f9f9;
}

.product-variations h3 {
    margin-bottom: 1rem;
    color: #333;
    font-weight: 600;
}

.variation-options {
    display: grid;
    gap: 0.75rem;
    margin-bottom: 1.5rem;
}

.variation-option {
    position: relative;
}

.variation-option input[type="radio"] {
    position: absolute;
    opacity: 0;
    width: 0;
    height: 0;
}

.variation-label {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 0.75rem 1rem;
    border: 2px solid #ddd;
    border-radius: 6px;
    background-color: white;
    cursor: pointer;
    transition: all 0.2s ease;
}

.variation-label:hover {
    border-color: #007bff;
    background-color: #f0f8ff;
}

.variation-option input[type="radio"]:checked + .variation-label {
    border-color: #007bff;
    background-color: #e3f2fd;
    box-shadow: 0 0 0 2px rgba(0, 123, 255, 0.25);
}

.variation-size {
    font-weight: 500;
    color: #333;
}

.variation-price {
    font-weight: 600;
    color: #28a745;
    font-size: 1.1em;
}

.variation-cart-section {
    padding-top: 1rem;
    border-top: 1px solid #ddd;
}

.selected-variation-info {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 1rem;
    padding: 0.5rem;
    background-color: white;
    border-radius: 4px;
}

.selected-title {
    font-weight: 500;
    color: #333;
}

.selected-price {
    font-weight: 600;
    color: #28a745;
    font-size: 1.2em;
}

.quantity-selector {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    margin-bottom: 1rem;
}

.quantity-selector input {
    width: 60px;
    padding: 0.25rem;
    border: 1px solid #ddd;
    border-radius: 4px;
    text-align: center;
}

.add-to-cart-variation {
    width: 100%;
    padding: 0.75rem;
    font-size: 1.1em;
    font-weight: 600;
}

/* Responsive Design */
@media (min-width: 768px) {
    .variation-options {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 1rem;
    }
}

@media (min-width: 1024px) {
    .variation-cart-section {
        display: flex;
        align-items: center;
        gap: 1rem;
    }
    
    .selected-variation-info {
        flex: 1;
        margin-bottom: 0;
    }
    
    .quantity-selector {
        margin-bottom: 0;
    }
    
    .add-to-cart-variation {
        width: auto;
        min-width: 150px;
    }
}
```

### JavaScript Functionality

```javascript
// Product Variation Selector JavaScript
document.addEventListener('DOMContentLoaded', function() {
    const variationInputs = document.querySelectorAll('input[name="product_variation"]');
    const selectedTitle = document.getElementById('selected-title');
    const selectedPrice = document.getElementById('selected-price');
    const addToCartBtn = document.querySelector('.add-to-cart-variation');
    const quantityInput = document.getElementById('quantity');
    
    // Update selected variation display
    function updateSelectedVariation() {
        const checkedInput = document.querySelector('input[name="product_variation"]:checked');
        if (checkedInput) {
            const label = checkedInput.nextElementSibling;
            const size = label.querySelector('.variation-size').textContent;
            const price = label.querySelector('.variation-price').textContent;
            const baseTitle = 'Alkaline Water / Air Alkali'; // This should be dynamic
            
            selectedTitle.textContent = `${baseTitle} - ${size}`;
            selectedPrice.textContent = price;
            addToCartBtn.setAttribute('data-product-id', checkedInput.value);
        }
    }
    
    // Listen for variation changes
    variationInputs.forEach(input => {
        input.addEventListener('change', updateSelectedVariation);
    });
    
    // Add to cart functionality
    addToCartBtn.addEventListener('click', function() {
        const productId = this.getAttribute('data-product-id');
        const quantity = quantityInput.value;
        
        if (!productId) {
            alert('Please select a variation.');
            return;
        }
        
        // AJAX call to add to cart
        fetch('/cart/add/', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': getCookie('csrftoken')
            },
            body: JSON.stringify({
                product_id: productId,
                quantity: parseInt(quantity)
            })
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                // Update cart count
                updateCartCount(data.cart_count);
                // Show success message
                showToast('Product added to cart successfully!', 'success');
            } else {
                showToast('Error adding product to cart.', 'error');
            }
        })
        .catch(error => {
            console.error('Error:', error);
            showToast('Error adding product to cart.', 'error');
        });
    });
    
    // Initialize with default selection
    updateSelectedVariation();
});

// Helper functions
function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

function updateCartCount(count) {
    const cartCountElement = document.querySelector('.cart-count');
    if (cartCountElement) {
        cartCountElement.textContent = count;
    }
}

function showToast(message, type = 'info') {
    // Implementation depends on your toast/notification system
    // This is a simple alert fallback
    alert(message);
}
```

### 1. Product Model Updates

```python
# products/models.py
class Product(models.Model):
    # Existing fields...
    parent_product = models.ForeignKey(
        'self', 
        on_delete=models.CASCADE, 
        null=True, 
        blank=True,
        related_name='variations'
    )
    is_variation = models.BooleanField(default=False)
    variation_type = models.CharField(
        max_length=50, 
        blank=True,
        choices=[
            ('size', 'Size'),
            ('color', 'Color'),
            ('weight', 'Weight'),
            ('pack', 'Pack Size'),
        ]
    )
    variation_value = models.CharField(max_length=100, blank=True)
    
    def get_variations(self):
        """Get all variations of this product."""
        if self.is_variation:
            return self.parent_product.variations.all() if self.parent_product else Product.objects.none()
        return self.variations.all()
    
    def get_base_product(self):
        """Get the base product (parent) for variations."""
        return self.parent_product if self.is_variation else self
    
    class Meta:
        ordering = ['name', 'variation_value']
```

### 2. Views Update

```python
# products/views.py
def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug)
    
    # Get all variations for this product
    if product.is_variation:
        base_product = product.parent_product
        variations = base_product.variations.all()
        main_product = base_product
    else:
        base_product = product
        variations = product.variations.all()
        main_product = product
    
    context = {
        'product': main_product,
        'current_variation': product,
        'variations': variations,
        'has_variations': variations.exists(),
    }
    
    return render(request, 'products/product_detail.html', context)
```

### 3. Cart Add Endpoint Update

```python
# cart/views.py
from django.http import JsonResponse
from django.views.decorators.http import require_http_methods
import json

@require_http_methods(["POST"])
def add_to_cart_ajax(request):
    try:
        data = json.loads(request.body)
        product_id = data.get('product_id')
        quantity = int(data.get('quantity', 1))
        
        # Handle both product slug and ID
        if product_id.isdigit():
            product = get_object_or_404(Product, id=product_id)
        else:
            product = get_object_or_404(Product, slug=product_id)
        
        # Add to cart logic (existing)
        cart = request.session.get('cart', {})
        cart_key = str(product.id)
        
        if cart_key in cart:
            cart[cart_key]['quantity'] += quantity
        else:
            cart[cart_key] = {
                'quantity': quantity,
                'price': str(product.price)
            }
        
        request.session['cart'] = cart
        request.session.modified = True
        
        # Calculate cart count
        cart_count = sum(item['quantity'] for item in cart.values())
        
        return JsonResponse({
            'success': True,
            'cart_count': cart_count,
            'message': f'{product.name} added to cart successfully!'
        })
        
    except Exception as e:
        return JsonResponse({
            'success': False,
            'message': 'Error adding product to cart.'
        }, status=400)
```

### 4. URL Configuration

```python
# cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    # Existing URLs...
    path('add/', views.add_to_cart_ajax, name='add_ajax'),
]
```

### product_detail.html Updates

```html
<!-- Replace the existing "Customers also bought" section -->
{% if has_variations %}
<div class="product-variations">
    <h3>Available Options</h3>
    <div class="variation-options">
        {% for variation in variations %}
        <div class="variation-option">
            <input type="radio" 
                   id="variation-{{ variation.id }}" 
                   name="product_variation" 
                   value="{{ variation.slug }}" 
                   data-price="{{ variation.price }}"
                   {% if variation.id == current_variation.id %}checked{% endif %}>
            <label for="variation-{{ variation.id }}" class="variation-label">
                <span class="variation-size">{{ variation.variation_value }}</span>
                <span class="variation-price">RM{{ variation.price }}</span>
            </label>
        </div>
        {% endfor %}
    </div>
    
    <div class="variation-cart-section">
        <div class="selected-variation-info">
            <span class="selected-title" id="selected-title">{{ product.name }} - {{ current_variation.variation_value }}</span>
            <span class="selected-price" id="selected-price">RM{{ current_variation.price }}</span>
        </div>
        <div class="quantity-selector">
            <label for="quantity">Quantity:</label>
            <input type="number" id="quantity" name="quantity" value="1" min="1" max="10">
        </div>
        <button type="button" class="btn btn-primary add-to-cart-variation" data-product-id="{{ current_variation.slug }}">
            Add to Cart
        </button>
    </div>
</div>
{% endif %}
```

### Before (Current Issues)
- ❌ Misleading "Customers also bought" title
- ❌ Multiple page navigations required
- ❌ No visual comparison of variations
- ❌ Missing product images create inconsistent UI
- ❌ Poor mobile experience

### After (Proposed Solution)
- ✅ Clear "Available Options" section title
- ✅ Single-page interaction with AJAX cart updates
- ✅ Visual radio button selection for easy comparison
- ✅ Consistent UI without image requirements
- ✅ Responsive design for all devices
- ✅ Real-time price updates
- ✅ Quantity selection per variation
- ✅ Toast notifications for cart updates

### Phase 1: Backend Foundation (Week 1)
1. Update Product model to support variations
2. Create data migration for existing products
3. Update product detail view
4. Create AJAX cart endpoint

### Phase 2: Frontend Implementation (Week 1-2)
1. Update product detail template
2. Implement CSS styling
3. Add JavaScript functionality
4. Test responsive design

### Phase 3: Testing & Refinement (Week 2)
1. Test variation selection functionality
2. Test AJAX cart operations
3. Verify mobile responsiveness
4. User acceptance testing

### Phase 4: Data Migration (Week 3)
1. Identify existing product relationships
2. Convert "customers also bought" data to variations
3. Update product slugs and URLs
4. Test data integrity

## Acceptance Criteria

- [ ] Remove "Customers also bought" section completely
- [ ] Implement radio button variation selector
- [ ] Add to cart works without page refresh
- [ ] Price updates dynamically when variation changes
- [ ] Quantity selector works for each variation
- [ ] Mobile-responsive design
- [ ] AJAX cart updates with proper error handling
- [ ] Toast notifications for user feedback
- [ ] Maintain existing cart functionality
- [ ] SEO-friendly URLs for variations
- [ ] Accessibility compliance (keyboard navigation, screen readers)
- [ ] Browser compatibility testing

### Performance
- Minimize AJAX calls
- Cache variation data
- Optimize database queries

### SEO
- Maintain canonical URLs for base products
- Implement structured data for variations
- Update sitemap generation

### Analytics
- Track variation selection events
- Monitor cart abandonment rates
- A/B test conversion improvements

### Accessibility
- Keyboard navigation support
- Screen reader compatibility
- High contrast mode support
- Focus indicators for radio buttons

---

**Priority**: HIGH - Critical UX improvement that affects core product browsing and purchasing flow.

**Estimated Effort**: 2-3 weeks

**Dependencies**: 
- Product model refactoring
- Frontend framework decision
- AJAX implementation
- Data migration strategy
